### PR TITLE
Make keyboard taps match to the music more

### PR DESCRIPTION
**Pull request by Sword352**

### CODE REVIEW

**Comment by libauror-a** [comment]
smh

**Comment by Sword352** [comment]
why

**Comment by libauror-a** [comment]
smh

**Comment by Sword352** [comment]
are you against improvements for the unholy engine

**Comment by Sword352** [comment]
unholy won't tolerate this...

**Comment by Sword352** [comment]
(i think)

**Comment by Sword352** [comment]
(please do not tolerate this @Unholywanderer :pleading_face:)

**Comment by libauror-a** [comment]
smh

**Comment by LeonGamerPS1** [comment]
shut the fuck up with your "smh"

**Comment by Unholywanderer** [comment]
smh

**Comment by CCobaltDev** [comment]
Thy end is now

**Comment by libauror-a** [comment]
> shut the fuck up with your "smh"


https://github.com/user-attachments/assets/3ca790ae-cb08-4667-8579-f547315cf9cf

**Comment by Sword352** [comment]
Can we stop spamming my email account this is annoying

**Comment by libauror-a** [comment]
you can unsubscribe from this pull request to stop getting notifications
if you dont want notifications to get pushed to your email at all you can go to your notifications settings and disable them from there

**Comment by Sword352** [comment]
Yeah I think I'm unsubscribing since this PR is like worthless 🥀

**Comment by LeonGamerPS1** [comment]
masturbating pigs

**Comment by LeonGamerPS1** [comment]
i see you.

Am Mi., 7. Mai 2025 um 20:27 Uhr schrieb Sword ***@***.***>:

**Pull request closed without merging**
